apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - pvc.yaml
  - route.yaml
  - service.yaml
  - template.yaml
  # - otel-collector-sidecar.yaml